### ISSUE TITLE
Lost fingerprint feature

### ISSUE THREAD

**Issue by snarkbe** [Magisk-Modules-Alt-Repo/ktweak#2]
I installed version 1.1.2 on my Oneplus 7T running OxygenOS Open Beta 7.

After install and reboot, I lost access to the fingerprint scanner. The fingerprint logo was not displayed on the screen and putting the finger at the right place would not work. I also had a UI restart. 

All of this was solved after disabling the module in Magisk.

**Comment by tytydraco** [comment]
@snarkbe Do you still have this issue? Was it fixed with v1.2.2?

**Comment by snarkbe** [comment]
1.2.4 looks good so far. No SystemUI freezes or reboot, no problem with the fingerprint reader.
