### ISSUE TITLE
Do KTweak changes remain after uninstalling it?

### ISSUE THREAD

**Issue by cg00001** [Magisk-Modules-Alt-Repo/ktweak#32]
I installed it and I had issues at shut down -had to keep shutdown button pressed to turn off.
I uninstalled it and I noticed my SSD driver led keeps working -even when I run nothing.
Do I need to manually uninstall everything, and how?

**Comment by Nitrovenom** [comment]
Must be something else

**Comment by cg00001** [comment]
> Must be something else

I think you're right.
I reinstalled KTweak, enabled it via systemctl, and next shutdown was fine -I shut down again after that and again it closed fine.

**Comment by cg00001** [comment]
I found the culprit in the journal.
I had "/usr/bin/xset s off -dpms &" in my OpenBox autostart, and journal mentioned upower service found DPMS disabled so, shut down didn't finish.
Using "/usr/bin/xset s off  &" instead took care of the issue.

**Comment by cg00001** [comment]
It was the last update of ananicy-cpp-git that caused all this.
