### ISSUE TITLE
CPU Govenor

### ISSUE THREAD

**Issue by HerXayah** [Magisk-Modules-Alt-Repo/ktweak#8]
The Interactive CPU Govenor you set, is causing my Phone to autostart whenever i plug it into a charger in its fully off state.

**Comment by ghost** [comment]
If you are having issues with interactive governor. Try changing it using SPKM(Smart Pack Kernel Manager).

**Comment by Nitrovenom** [comment]
Use FKM to change sur

**Comment by tytydraco** [comment]
> The Interactive CPU Govenor you set, is causing my Phone to autostart whenever i plug it into a charger in its fully off state.

Are you running a custom kernel? Give me the relevant data.

**Comment by eebssk1** [comment]
Don't use interactive scheduler on EAS kernel.
Just a note.
